import { Inject, Injectable, Logger } from '@nestjs/common';
import * as fs from 'fs/promises';
import * as path from 'path';
import type { INginxBlocklistWriter } from '../../domain/interfaces/nginx-blocklist.writer';
import {
  NGINX_RUNTIME_REPOSITORY,
  type INginxRuntimeRepository,
} from '../../../nginx/domain/interfaces/nginx-runtime.repository';

const NGINX_CONF_DIR = path.resolve(
  __dirname,
  '../../../../../../nginx/conf.d',
);
const BLOCKLIST_FILE = path.join(NGINX_CONF_DIR, 'ip-blocklist.conf');

@Injectable()
export class NginxBlocklistWriterImpl implements INginxBlocklistWriter {
  private readonly logger = new Logger(NginxBlocklistWriterImpl.name);

  constructor(
    @Inject(NGINX_RUNTIME_REPOSITORY)
    private readonly runtime: INginxRuntimeRepository,
  ) {}

  async apply(ips: string[]): Promise<{ reloaded: boolean; output: string }> {
    const content = this.renderConfig(ips);
    await fs.mkdir(NGINX_CONF_DIR, { recursive: true });
    await fs.writeFile(BLOCKLIST_FILE, content, 'utf-8');

    const test = await this.runtime.testConfig();
    if (!test.success) {
      this.logger.error(`nginx -t failed, skipping reload: ${test.output}`);
      return { reloaded: false, output: test.output };
    }

    const reload = await this.runtime.reload();
    if (!reload.success) {
      this.logger.error(`nginx reload failed: ${reload.output}`);
      return { reloaded: false, output: reload.output };
    }

    this.logger.log(`nginx blocklist applied: ${ips.length} entries`);
    return { reloaded: true, output: reload.output };
  }

  private renderConfig(ips: string[]): string {
    const header = [
      '# Auto-generated by kscold-control SecurityModule.',
      '# Source of truth: ip_bans table. DO NOT EDIT MANUALLY.',
      `# Last sync: ${new Date().toISOString()}`,
      '',
    ].join('\n');

    if (ips.length === 0) {
      return `${header}# (no active bans)\n`;
    }

    const body = ips.map((ip) => `deny ${ip};`).join('\n');
    return `${header}${body}\n`;
  }
}
